// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CpVyQ5hL85hZYxlIg_Z_IFaLzINHP8k',
    appId: '1:452014556538:web:426325f25d625d83d0c2c3',
    messagingSenderId: '452014556538',
    projectId: 'diabetes-companio',
    authDomain: 'diabetes-companio.firebaseapp.com',
    storageBucket: 'diabetes-companio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYWTybnRIPV3XwpA219lu7dTrBV5txdw',
    appId: '1:452014556538:android:60d782a48db6b057d0c2c3',
    messagingSenderId: '452014556538',
    projectId: 'diabetes-companio',
    storageBucket: 'diabetes-companio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7bb7LSBpgnF2BP3cyPTp4D1xWn9YQQL4',
    appId: '1:452014556538:ios:f5e9f685e07b2dd6d0c2c3',
    messagingSenderId: '452014556538',
    projectId: 'diabetes-companio',
    storageBucket: 'diabetes-companio.appspot.com',
    iosBundleId: 'com.example.diabetesCompanio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7bb7LSBpgnF2BP3cyPTp4D1xWn9YQQL4',
    appId: '1:452014556538:ios:dc7c8e86a0f5826ad0c2c3',
    messagingSenderId: '452014556538',
    projectId: 'diabetes-companio',
    storageBucket: 'diabetes-companio.appspot.com',
    iosBundleId: 'com.example.diabetesCompanio.RunnerTests',
  );
}
