// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnabCHW2i7xzz8uhhvGTgQXT6_55tt3sw',
    appId: '1:787595921516:web:660241566c261d4812b049',
    messagingSenderId: '787595921516',
    projectId: 'companio-diabetes-app',
    authDomain: 'companio-diabetes-app.firebaseapp.com',
    storageBucket: 'companio-diabetes-app.appspot.com',
    measurementId: 'G-NKTDZ3EVXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0zenovt_S-Lv_yD_fFzzQ2ov-RXgokc',
    appId: '1:787595921516:android:003f0b3c5df8bc7412b049',
    messagingSenderId: '787595921516',
    projectId: 'companio-diabetes-app',
    storageBucket: 'companio-diabetes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABuyz42O5By60f3l7u1PoKWJQCec0vTdU',
    appId: '1:787595921516:ios:272048d05db4d77412b049',
    messagingSenderId: '787595921516',
    projectId: 'companio-diabetes-app',
    storageBucket: 'companio-diabetes-app.appspot.com',
    iosBundleId: 'com.example.companioDiabetesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABuyz42O5By60f3l7u1PoKWJQCec0vTdU',
    appId: '1:787595921516:ios:cb38fbe636bc9f4112b049',
    messagingSenderId: '787595921516',
    projectId: 'companio-diabetes-app',
    storageBucket: 'companio-diabetes-app.appspot.com',
    iosBundleId: 'com.example.companioDiabetesApp.RunnerTests',
  );
}
